### ISSUE TITLE
Support for postCSS

### ISSUE THREAD

**Issue by nolimit-developers** [junstyle/vscode-css-formatter#1]
Hello, your plugin for VS Code is awesome but i would need support for postcss. Is it possible to add it?

**Comment by junstyle** [comment]
this is just a tool for formatting css.
what postcss?
you can resolve postcss at first, then use this to format

**Comment by nolimit-developers** [comment]
Ok, If I switch to CSS in VS Code, the Formatter works correctly. But if the file is in PostCSS language, then in the context menu "Format With CSS Formatter" is not active / is not found.

**Comment by junstyle** [comment]
i don't know what postcss language. do you mean sass/less? 

you can search and install sass related extension to format sass files.

**Comment by nolimit-developers** [comment]
https://postcss.org/ it may have slightly different syntax and it's usually css. Your plugin is good, but it has some limitations, it does not recognize e.g. @mixin, wrap the line with a brace

**Comment by junstyle** [comment]
i think you should known the difference about css and sass/less(you mean postcss).

my extension is a formatter for css.

postcss is a tool for transform sass or less to css.

generally postcss used in react/vue project.

**Comment by junstyle** [comment]
as a formatter, it do not modify user's codes.

if you want to use postcss to transform some css rules, you should install other extension to do this. and then use this extension to format.

@mixin is valid in css?
